---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app1
  namespace: flux-system
spec:
  # dependsOn:
  # - name: observability
  interval: 1m0s
  path: ./deploy/cluster1/app1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
