---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  # dependsOn:
  # - name: observability
  interval: 1m0s # detect drift and undo kubectl edits every minute
  prune: true # remove stale resources from cluster
  path: ./deploy/cluster1/ # This is where the cluster kustomization.yaml resides
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system # points to namespace where this GitRepository is
